[build]
command = ""
publish = "."

[[headers]]
  for = "/index.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
